version: '3.7'

services:
    chatserver:      
      build:
         context: .
         dockerfile: ./Dockerfile
      ports:
        - "9000:9000"
      environment:
        - ENV_CHAT_SERVER_PORT=9000
        - ENV_CHAT_SERVER_LOG_PATH="/log"
        - RedisConnection=chat_redis
      volumes:
        - "../data/ChatServer:/server/log"
      links:
        - "chat_redis"
      depends_on:
        - "chat_redis"

    chat_redis:
      container_name: chat_redis
      image: redis:6.2
      volumes:
        - "../data/redis:/usr/local/redis/data"
      ports:
        - "6379:6379"
        
